# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    env:
      GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    name: Build and deploy
    runs-on: macos-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.1'
      - name: Install Ruby Dependencies
        run: bundle install
      - name: Install Fastlane
        run: gem install fastlane -no-rdoc --no-document
      - name: Run Unit Test
        run: bundle exec fastlane run_test_suite
      - name: Run xcov
        run: bundle exec fastlane run_xcov
      - name: Run Danger
        run: bundle exec danger --verbose
      - name: show contents of report files
        run: sh print-report.sh
      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.11
