# .github/workflows/documentation.yml
name: Documentation

on: [push]

jobs:
  build:
    env:
      GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Sources"
          module-name: XCCov-Demo
          output: "Documentation"
      - name: do git push
        run: |
              git config --global user.email "abhinav.dobhal@telusinternational.com"
              git config --global user.name "abhinav-ti"

              #git add filename.ext
              git add Documentation
              git commit -m "message"

              git push https://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@github.com/abhinav2014/XCCov-Demo.git HEAD:master -q

#      - name: Upload Documentation to Wiki
#        uses: SwiftDocOrg/github-wiki-publish-action@v1
#        with:
#          path: "Documentation"
#        env:
#          GH_PERSONAL_ACCESS_TOKEN: "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"
